# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            paulmarinos.github.io
tagline:          'my notes'
description:      'things I want to remember, reference, and share'
url:              https://paulmarinos.github.io
baseurl:          /

author:
  name:           'Paul Marinos'
  url:            https://linkedin.com/in/paulmarinos

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/paulmarinos/paulmarinos.github.io
